import { Container, Grid } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { LoginBox } from '../components/login-box'
import { MessageList } from '../components/message-list'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container h="100vh" maxW="70rem">
        <Grid templateColumns="1fr 453px" gap={30}>
          <MessageList />
          <LoginBox />
        </Grid>
      </Container>
    </div>
  )
}

export default Home
